name: Notifications

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '5 1/4 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
        name: Prepare script
      - run: npm run start
        name: Get portfolio values
        env:
          ICETRACKER_TARGET_BALANCE: ${{ secrets.TargetBalance }}
          ICETRACKER_STATE_FILE_ENCRYPTION_KEY: ${{ secrets.EncryptionKey }}
          ICETRACKER_STATE_FILE: ${{ secrets.StateFileName }}
          ICETRACKER_REFILL_LEVEL: ${{ secrets.RefillPercent }}
          ICETRACKER_TAKEPROFIT_LEVEL: ${{ secrets.TakeprofitPercent }}
          ICETRACKER_SHRIMPY_API_KEY: ${{ secrets.ShrimpyApiKey }}
          ICETRACKER_SHRIMPY_API_SECRET: ${{ secrets.ShrimpyApiSecret }}
          ICETRACKER_IGNORED_ACCOUNTS: ${{ secrets.IgnoredAccounts }}
          ICETRACKER_BASE_CURRENCY: ${{ secrets.BaseCurrency }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Update state
        with:
          commit_message: State update
          file_pattern: '*.state *.state.nonce'
      - name: Check if there are required actions
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "actions.txt"
      - name: Read required actions
        if: steps.check_files.outputs.files_exists == 'true'
        id: actions
        uses: juliangruber/read-file-action@v1
        with:
          path: ./actions.txt
      - name: Send email
        if: steps.check_files.outputs.files_exists == 'true'
        uses: cinotify/github-action@main
        with:
          to: ${{ secrets.NotificationEmail }}
          subject: 'Ice Tracker: Action required'
          body: ${{ steps.actions.outputs.content }}
